### ISSUE TITLE
Changes not saved

### ISSUE THREAD

**Issue by Matt-Lengenfelder** [rajyraman/Dataverse-LINQPad-Driver#10]
When I try to save some changes like this:

var c = Contact.Where(x=>x.hmn_autonumber == "C-0001007506" ).FirstOrDefault();
c.FirstName = "Test";
SaveChanges();

It doesn't save the changes. What am I doing wrong, or is this connection not able to update the database? Looking into this further, I think it's probably just not supported to do it this way. Maybe if I used the Dataverse.Retrieve, but I gave that a go and wasn't able to get it to work. If someone has an example that would be great, but if it's not possible then that's ok too. Very useful tool regardless. I wonder how xrmtoolbox sql4cds works in comparison to this? I know I can run updates from there, I just prefer linqpad/C# over sql.

**Comment by rajyraman** [comment]
@Matt-Lengenfelder - You need to UpdateObject(c) before SaveChanges(). Since, this just uses the SDK, every action possible through the SDK/API is possible through LINQPad.

**Comment by Matt-Lengenfelder** [comment]
Thank you, I'll have to take some time to readup on the API. Maybe add this and a link to the API documents in your readme for those of us who are not yet familiar with it?
