### ISSUE TITLE
Feature Request - Get Table By Name

### ISSUE THREAD

**Issue by bseng** [rajyraman/Dataverse-LINQPad-Driver#13]
Hi, 

Thanks for making this library.

Can we have a method GetTableByName so we can do something like 

`(from u in this.GetTableByName(Tables.SystemUser) select u)`

Thanks.

**Comment by rajyraman** [comment]
@bseng - You can already query like this.

![image](https://user-images.githubusercontent.com/5035266/150266263-65472568-d4ae-4df9-8d22-3f6d4b5dd54a.png)

If you have LINQPad Premium, you can see the list of tables as well.

![image](https://user-images.githubusercontent.com/5035266/150266404-07297a20-ddf6-4ea4-8373-0ea5edf215fc.png)

**Comment by bseng** [comment]
Hi @rajyraman ,

My example is not clear.

I want to resolve the IOrderedQueryable<table> by the table name as a string.

so 

`from w from this.GetTableByName("msdyn_workordertype") select w`

**Comment by rajyraman** [comment]
@bseng - This should work.

![image](https://user-images.githubusercontent.com/5035266/150269084-59f21ce9-1e05-4596-ae5f-d69c643c74e2.png)

**Comment by bseng** [comment]
It works thanks!
