### ISSUE TITLE
UserLocalizedLabel possible null checking

### ISSUE THREAD

**Issue by PandaBoy00** [rajyraman/Dataverse-LINQPad-Driver#14]
In the file DynamicsDriver.cs, Line 219.  It is possible that there is a missing null checking in which would cause a Object Reference not found.  By doing null checking on UserLocalizedLabel would solve the bug and not cause an exception.

**Comment by rajyraman** [comment]
@PandaBoy00 - Are you getting a null reference exception?

**Comment by PandaBoy00** [comment]
Yes and what i did want to add `?.` for checking before use and it was resolved.

The full line of code is `select new { a.Label, a.Value, SanitisedLabel = a.Label.UserLocalizedLabel?.Label.Sanitise() }`

**Comment by rajyraman** [comment]
@PandaBoy00 - New release fixes this issue.
