### ISSUE TITLE
Error when populating context

### ISSUE THREAD

**Issue by RoyChase** [rajyraman/Dataverse-LINQPad-Driver#19]
When creating a connection the connection sits at "populating" and, after a couple of minutes, displays the following error:

![image](https://github.com/rajyraman/Dataverse-LINQPad-Driver/assets/4084743/32e1799a-9682-4b5e-9c25-1a721bcbb55e)

It happens if I try Azure, OAuth or Client Secret connection types and I can successfully connect from code using them.

**Comment by rajyraman** [comment]
@RoyChase - this looks like a invalid class or optionsetname during earlybound entity generation. Do you have any entities or global optionsets with word "event" in them?

**Comment by RoyChase** [comment]
There is a Table with Display name `Event` and logical name `event`.  It's tagged as a managed table.  I'm not interested n that particular table as, at the moment, I'm only interested in a few custom tables.

**Comment by yarin12** [comment]
I'm experiencing the same issue as a I do have the table "Event" from msft_EventAnalytics. Microsoft Analytics. Is there any fix for this issue?

**Comment by rajyraman** [comment]
@RoyChase @yarin12 - Published new version to Nuget. Can you please check if it fixes your issue? I was able to test this only via debugger and I could not create Event entity without any prefix.

https://www.nuget.org/packages/NY.Dataverse.LINQPadDriver/1.7.4

**Comment by RoyChase** [comment]
@rajyraman The update has fixed the problem.

Thank you
