### ISSUE TITLE
SQL tab does not display fetchXml

### ISSUE THREAD

**Issue by bwmodular** [rajyraman/Dataverse-LINQPad-Driver#2]
For some reason, the SQL tab remains blank for me, even though the queries are working succesfully.
Using version 1.2 of the driver from NuGet.
![image](https://user-images.githubusercontent.com/1889586/105487855-a7898200-5ca8-11eb-8816-6707d35c00f8.png)

**Comment by rajyraman** [comment]
@bwmodular - Use the latest version 1.4.0-alpha.

**Comment by bwmodular** [comment]
That's fixed it. Thanks! Sorry I didn't spot the 'use pre-release' bit in your instructions!
