### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by Matt-Lengenfelder** [rajyraman/Dataverse-LINQPad-Driver#20]
![image](https://github.com/rajyraman/Dataverse-LINQPad-Driver/assets/5349485/d5073821-074e-4303-a50a-8b643d3fafd0)

I'm seeing this security vulnerability when installing this driver in linqpad. That specifies Azure.Identity 1.10.1 If I'm using a client id/client secret that wouldn't be using OAuth 1.10.1 so I wouldn't need to worry about this right? or would that still somehow tie into OAuth 1.10.1 ?

**Comment by Matt-Lengenfelder** [comment]
it looks like Azure Identity 1.10.3 fixes the vulnerability.

https://github.com/dotnet/SqlClient/issues/2212

![image](https://github.com/rajyraman/Dataverse-LINQPad-Driver/assets/5349485/a7a35c61-670e-4ef9-be61-ad981dd1c1f3)

**Comment by Matt-Lengenfelder** [comment]
> or would that still somehow tie into OAuth 1.10.1 ?

Using a client id/client secret is still using OAuth, so using this plugin to authenticate is probably a bad idea until this security issue is resolved. I did grab the repo and just updated it to use the 1.10.3 and took the compiled dll's and replaced the old version everywhere on my sytem with the new version. I was able to authenticate and run a query, but I get errors so maybe there needs to be other changes, or maybe there's some other issue with updating the dll's like I did.

I'd need to learn more about xrmtoolbox plugins to further troubleshoot it. But for now I'm not going to be using this driver with linqpad.

**Comment by rajyraman** [comment]
@Matt-Lengenfelder - I already updated it las t month. You can try updating this from LINQPad itself to the latest version.

https://github.com/rajyraman/Dataverse-LINQPad-Driver/commit/50193e9c0a521746737824f978f8eaa7b2a8a14c

https://www.nuget.org/packages/NY.Dataverse.LINQPadDriver/#releasenotes-body-tab

**Comment by rajyraman** [comment]
@Matt-Lengenfelder - I updated it just last month.

https://github.com/rajyraman/Dataverse-LINQPad-Driver/commit/50193e9c0a521746737824f978f8eaa7b2a8a14c

I will try updating the packages again.

**Comment by rajyraman** [comment]
@Matt-Lengenfelder - Updated Azure Identity to 1.10.4 and Dataverse Client to 1.3.0 packages. The latest version is 1.7.5.

https://www.nuget.org/packages/NY.Dataverse.LINQPadDriver/1.7.5
