### ISSUE TITLE
CDS Environment URL

### ISSUE THREAD

**Issue by Matt-Lengenfelder** [rajyraman/Dataverse-LINQPad-Driver#5]
Should the CDS Environment URL look something like this: https://<organization-name>.crm.dynamics.com
or does it need to point to the API? I'm on GCC government security Dataverse so it's very possible that's why it's not working. But I thought I would ask and make sure that the Environment URL should look like this: 
https://<organization-name>.crm.dynamics.com

**Comment by rajyraman** [comment]
@Matt-Lengenfelder - It is the base URL. These inputs are used to construct the connection string, so use the same format as you would in a connection string. https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect#named-account-using-microsoft-365

**Comment by Matt-Lengenfelder** [comment]
Thanks.
