### ISSUE TITLE
Incorrect Web API OData query

### ISSUE THREAD

**Issue by devkeydet** [rajyraman/Dataverse-LINQPad-Driver#7]
Example LINQ query in LINQPad:
_(from a in Account
where a.Name.StartsWith("foo")
select new { a.Name }).Take(10)_

This produces a successful result.  However, the WebAPI URL produced is not valid.  Here is what is produced:
_https://your-environment-here.crm.dynamics.com/api/data/v9.1/accounts?$select=name&$filter=((startswith(name,'foo'))) and ()&$top=10_

Here's what should be produced:
_https://your-environment-here.crm.dynamics.com/api/data/v9.1/accounts?$filter=startswith(name,'foo')&$top=10&$select=name_

**Comment by rajyraman** [comment]
@devkeydet - Missed testing the simplest of queries. 🤦🏻. Published 1.6.1-alpha to nuget.
